future: true
permalink: /:title/
url: http://hongzhw.github.io
name: hongzhw
author: hongzhw
qq: 1023174108
email: 1023174108@qq.com

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: hongzhw
about: "这里是hongzhw的个人博客，创建于 2018 年。"

safe: true
paginate: 20
